version: '3'

services:
  predictor-service:
    container_name: predictor-service
    restart: always
    ports:
      - 80:80
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./configs/prod.yml:/app/configs/config.yml
      - ./logs:/app/logs
    networks:
      - prod-network

networks:
  prod-network:
    name: prod-network